config/routes.rb
TimecopWeb::Engine.routes.draw do
  root "main#index"
  post "/" => "main#travel", as: :travel
end

app/controllers/timecop_web/application_controller.rb
module TimecopWeb
  class ApplicationController < ActionController::Base
    protect_from_forgery with: :exception
  end
end

app/controllers/timecop_web/main_controller.rb
require_dependency "timecop_web/application_controller"

module TimecopWeb
  class MainController < ApplicationController
    def index
    end

    def travel
      case params[:commit]
      when "travel" then Timecop.travel(move_at)
      when "freeze" then Timecop.freeze(move_at)
      else Timecop.return
      end

      redirect_to root_path
    end

    private

    def move_at
      @more_at ||= begin
        Time.zone.parse %(#{travel_params["m(1i)"]}-#{travel_params["m(2i)"]}-#{travel_params["m(3i)"]} #{travel_params["m(4i)"]}:#{travel_params["m(5i)"]})
      end
    end

    def travel_params
      params.require(:travel).permit(:"m(1i)", :"m(2i)", :"m(3i)", :"m(4i)", :"m(5i)")
    end
  end
end

app/helpers/timecop_web/application_helper.rb
module TimecopWeb
  module ApplicationHelper
  end
end

app/views/layouts/timecop_web/application.html.slim
doctype html
html
  head
    title timecop web
    meta name="viewport" content="width=device-width,initial-scale=1"
    = csrf_meta_tags
    = stylesheet_link_tag "//maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.4/css/bootstrap.min.css"
    css:
      #main {
        margin-top: 5.5rem;
      }
      footer {
        padding: 1.5rem 0;
        font-size: 80%;
        color: #888;
      }
  body
    = render partial: "shared/timecop_web/header"

    .container-fluid#main
      - if notice
        .alert.alert-success role="alert"
          small = notice
      - if alert
        .alert.alert-warning role="alert"
          small = alert
      = yield

    = render partial: "shared/timecop_web/footer"

app/views/shared/timecop_web/_footer.html.slim
footer
  .container-fluid
    ul.nav.nav-inline
      li.nav-item Powered by #{link_to "timecop web", "https://github.com/yhirano55/timecop_web", class: "nav-link"} #{TimecopWeb::VERSION}

app/views/shared/timecop_web/_header.html.slim
header
  nav.navbar.navbar-fixed-top.navbar-dark.bg-inverse
    .nav.navbar-nav
      = link_to "timecop web", root_path, class: "nav-item nav-link active"

app/views/timecop_web/main/index.html.slim
.row
  .col-md-12
    .card
      .card-block
        - if stack_item = Timecop.top_stack_item
          p.card-text #{I18n.l(stack_item.time, format: :long)} <span class="tag tag-danger">#{stack_item.mock_type}</span>
        - else
          p.card-text #{I18n.l(Time.current, format: :long)} <span class="tag tag-info">present</span>
        = form_for(OpenStruct.new, as: :travel, url: travel_path, html: { class: "form-inline" }) do |f|
          .form-group
            = f.datetime_select :m, { start_year: 1940 }, class: "form-control"
          .btn-group.m-l-1 role="group"
            = f.submit :travel, class: "btn btn-outline-primary"
            = f.submit :freeze, class: "btn btn-outline-primary"
            = f.submit :return, class: "btn btn-outline-primary"